import { chromium } from '@playwright/test'
const browser = await chromium.launch({ channel: 'chromium', args: ['--use-angle=gl-egl', '--use-gl=angle', '--enable-gpu', '--ignore-gpu-blocklist'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errs = []; page.on('pageerror', (e) => errs.push(String(e)))
await page.goto((process.argv[2] ?? 'http://127.0.0.1:5173/') + '?replay=michaung2023')
await page.waitForSelector('.panel.left', { timeout: 120000 })
await page.fill('.search input', process.env.HG_ADDRESS ?? 'Arumugam Road')
await page.waitForSelector('.suggest li'); await page.locator('.suggest li').first().dispatchEvent('mousedown')
const t0 = Date.now()
await page.waitForSelector('text=/Move your car to|No dry way out/', { timeout: 180000 }).catch(() => {})
console.log('decision after', Math.round((Date.now() - t0) / 1000), 's:', await page.locator('.decision').textContent().catch(() => null))
console.log('route line:', await page.locator('p[role=status]').first().textContent().catch(() => null))
await page.waitForTimeout(2500)
await page.screenshot({ path: process.argv[3] ?? '/tmp/leaveby.png', timeout: 120000 })
console.log('errors', errs)
await browser.close()
