// After a failed plan offline (no pack), does planning recover when the network comes back, without a reload?
import { launch, open, PROD, OUT, sleep, waitCard, panelText, save } from './lib.mjs'
const b = await launch()
const { ctx, page, log } = await open(b)
await page.goto(PROD + '?replay=michaung2023&motion=off')
await page.evaluate(async () => { await navigator.serviceWorker.ready })
await page.reload()
await page.waitForFunction(() => !!navigator.serviceWorker.controller, null, { timeout: 15000 })
await waitCard(page); await sleep(3000)
await ctx.setOffline(true)
await page.getByRole('button', { name: 'Take me to dry ground' }).click()
await page.waitForSelector('.go [role=alert], .go-result:not(.stale)', { timeout: 30000 }).catch(() => {})
await sleep(1000)
const a = (await panelText(page, '.go')).split('\n').filter((l) => /Could not|min (by|on)|No route/.test(l)).join(' | ')
console.log('offline (no reload, no pack):', a)
await ctx.setOffline(false)
await sleep(4000)
for (const m of ['Car', 'On foot', 'Two-wheeler']) {
  await page.getByRole('button', { name: m, exact: true }).click(); await sleep(5000)
  console.log(`online again, ${m}:`, (await panelText(page, '.go')).split('\n').filter((l) => /Could not|min (by|on)|No route/.test(l)).join(' | '))
}
await page.screenshot({ path: `${OUT}/t3b_back_online_still_failing.png` })
await page.getByRole('button', { name: 'Close' }).first().click()
await page.getByRole('button', { name: 'Take me to dry ground' }).click(); await sleep(5000)
console.log('close + reopen online:', (await panelText(page, '.go')).split('\n').filter((l) => /Could not|min (by|on)|No route/.test(l)).join(' | '))
await page.reload(); await waitCard(page); await sleep(2000)
await page.getByRole('button', { name: 'Take me to dry ground' }).click()
await page.waitForSelector('.go [role=alert], .go-result:not(.stale)', { timeout: 30000 }).catch(() => {})
console.log('after reload online:', (await panelText(page, '.go')).split('\n').filter((l) => /Could not|min (by|on)|No route/.test(l)).join(' | '))
await b.close()
